import test from 'node:test'; import assert from 'node:assert/strict';
import {RNG} from '../src/core/rng.js'; import {generateFamily} from '../src/family/family_generator.js'; import {Game} from '../src/core/game.js';

test('same seed generates identical family',()=>assert.deepEqual(generateFamily(new RNG('abc-123')),generateFamily(new RNG('abc-123'))));
test('different seeds generate different families',()=>assert.notDeepEqual(generateFamily(new RNG('alpha')),generateFamily(new RNG('beta'))));
test('parents are biologically plausible at birth',()=>{for(let i=0;i<500;i++){const f=generateFamily(new RNG(`p-${i}`));assert.ok(f.parents.mother.age>=21&&f.parents.mother.age<=39);assert.ok(f.parents.father.age>=20);}});
test('grandparents are older than their children by at least 18 years',()=>{for(let i=0;i<300;i++){const f=generateFamily(new RNG(`g-${i}`));assert.ok(f.grandparents.maternal.grandmother.age-f.parents.mother.age>=18);assert.ok(f.grandparents.maternal.grandfather.age-f.parents.mother.age>=19);assert.ok(f.grandparents.paternal.grandmother.age-f.parents.father.age>=18);assert.ok(f.grandparents.paternal.grandfather.age-f.parents.father.age>=19);}});
test('siblings present at birth are always older and plausible',()=>{for(let i=0;i<500;i++){const f=generateFamily(new RNG(`s-${i}`));for(const s of f.siblings){assert.ok(s.age>=1);assert.ok(s.age<=f.parents.mother.age-18);}}});
test('player genetics stay in plausible ranges',()=>{for(let i=0;i<500;i++){const f=generateFamily(new RNG(`x-${i}`));assert.ok(f.player.appearance.heightCm>=145&&f.player.appearance.heightCm<=205);assert.ok(f.player.appearance.attractiveness>=1&&f.player.appearance.attractiveness<=100);assert.ok(f.player.health.constitution>=1&&f.player.health.constitution<=100);}});
test('household class and support metrics exist',()=>{const f=generateFamily(new RNG('house'));assert.ok(['düşük','orta','üst-orta','yüksek'].includes(f.household.economicClass));assert.ok(f.household.educationSupport>=0&&f.household.educationSupport<=100);assert.ok(f.household.hobbySupport>=0&&f.household.hobbySupport<=100);});
test('aging advances player and close family together',()=>{const g=new Game('aging');const ma=g.state.parents.mother.age;g.ageOneYear();assert.equal(g.state.player.age,1);assert.equal(g.state.year,2027);assert.equal(g.state.parents.mother.age,ma+1);});

test('grandparents age with the rest of the family',()=>{const g=new Game('grand-age');const before=g.state.grandparents.maternal.grandmother.age;g.ageOneYear();assert.equal(g.state.grandparents.maternal.grandmother.age,before+1);});
test('early childhood yearly simulation keeps stats bounded',()=>{for(let i=0;i<100;i++){const g=new Game(`child-${i}`);for(let y=0;y<6;y++)g.ageOneYear();assert.ok(g.state.player.health.current>=0&&g.state.player.health.current<=100);assert.ok(g.state.player.personality.curiosity>=0&&g.state.player.personality.curiosity<=100);}});
test('new siblings can be born after the player and are newborns',()=>{let births=0;for(let i=0;i<600;i++){const g=new Game(`birth-${i}`);const initial=g.state.siblings.length;for(let y=0;y<8;y++)g.ageOneYear();if(g.state.siblings.length>initial){births++;const newborns=g.state.siblings.filter(s=>s.id.startsWith('sibling-born-'));assert.ok(newborns.length>0);assert.ok(newborns.every(s=>s.age>=0&&s.age<=7));}}assert.ok(births>0);});
test('school start is not incorrectly stored as a major life-tree branch',()=>{const g=new Game('school-not-tree');let event=null;for(let i=0;i<7;i++){event=g.ageOneYear();if(event?.id==='school-start'){g.makeChoice(event,event.choices[0].id);break;}}assert.ok(g.state.education?.enrolled);assert.equal(g.state.lifeTree.nodes.length,0);});

test('primary school stores a procedural school and bounded quality',()=>{const g=new Game('school-data');let e;for(let i=0;i<7;i++){e=g.ageOneYear();if(e?.id==='school-start'){g.makeChoice(e,'embrace');break;}}assert.ok(g.state.education?.schoolName.endsWith('İlkokulu'));assert.ok(g.state.education.quality>=25&&g.state.education.quality<=95);});
test('annual action economy allows three distinct childhood actions but no same-action spam',()=>{const g=new Game('actions');for(let i=0;i<6;i++){const e=g.ageOneYear();if(e)g.makeChoice(e,e.choices[0].id);}assert.equal(g.state.actions.remaining,3);const ids=g.availableActivities().map(a=>a.id);assert.ok(ids.length>=3);const first=ids[0];g.performActivity(first);assert.throws(()=>g.performActivity(first),/zaten yaptın/);g.performActivity(ids[1]);g.performActivity(ids[2]);assert.equal(g.state.actions.remaining,0);});
test('procedural friends can form in school years',()=>{let found=0;for(let i=0;i<250;i++){const g=new Game(`friends-${i}`);for(let y=0;y<12;y++){const e=g.ageOneYear();if(e)g.makeChoice(e,e.choices[0].id);}if(g.state.social.friends.length)found++;}assert.ok(found>40);});
test('friends have plausible age distance',()=>{const g=new Game('friend-age');for(let y=0;y<14;y++){const e=g.ageOneYear();if(e)g.makeChoice(e,e.choices[0].id);}for(const f of g.state.social.friends)assert.ok(Math.abs(f.age-g.state.player.age)<=1);});
